export const LOGIN_STATE_NOT_LOGGED_IN = 0;
export const LOGIN_STATE_STARTED = 1;
export const LOGIN_STATE_LOGGED = 2;

export const ACTION_LOGIN_INFO = 'ACTION_LOGIN_INFO';
export const ACTION_LOGIN_STARTED = 'ACTION_LOGIN_STARTED';
export const ACTION_LOGOUT = 'ACTION_LOGOUT';
export const ACTION_LOGIN_DONE = 'ACTION_LOGIN';
export const ACTION_LOGIN_ERROR = 'ACTION_LOGIN_ERROR';
export const ACTION_ATUALIZA_CADASTRO = 'ACTION_ATUALIZA_CADASTRO';